### PR TITLE
Switch to pyproject.toml and remove setuptools run-time dep

### PR DESCRIPTION
**Pull request by twizmwazin**

### CODE REVIEW

**Comment by mahaloz** [comment]
@twizmwazin is there any way we can keep the setup.py and the pyproject.toml? Doing this kills support for Python 3.8, which is still the current version on Ubuntu 20.04

**Comment by twizmwazin** [comment]
We can keep the stub setup.py, but how does this remove support for python 3.8?

**Comment by twizmwazin** [comment]
Just to confirm, you can install my branch of BinSync in a fresh ubuntu 20.04 docker container with this:
```
apt update; apt install python3 python3-pip git
pip install "git+https://github.com/twizmwazin/binsync.git@modern-packaging"
```

**Comment by mahaloz** [comment]
@twizmwazin does editable build work too? I could've sworn it did not work... strange

**Comment by twizmwazin** [comment]
Editable doesn't work if you're trying to install it with the ubuntu version of pip, but it works fine in a venv where you've upgraded pip. I think this is a reasonable requirement since it is only for dev setups.

**Pull request merged**
