### PR TITLE
Globals panel fix

### PR DESCRIPTION
**Pull request by ColdMeekly**
This commit fixes the following crash and fixes the Type field not being populated:
```
Traceback (most recent call last):
  File "C:\Users\Username\AppData\Local\Programs\Python\Python39\lib\site-packages\binsync\ui\force_push\panels\globals_table.py", line 55, in data
    return f"{hex(self.row_data[row][0])} {self.row_data[row][1]}"
TypeError: 'str' object cannot be interpreted as an integer
```
This happened because `row_data` returns `['EGameStateType', '', 'Enum']`. The commit stops casting the name to hex, as well as switched to retrieving the type from the 2nd index instead of the 1st.

There's still an issue where this name (`EGameStateType`) is populating the `Addr` field instead of the `Name` field. Screenshot attached.
image

### CODE REVIEW

**Comment by mahaloz** [comment]
@ColdMeekly, but what happens in the case of global vars, which are keyed by address? Have you tried to see what happens with them?

**Comment by ColdMeekly** [comment]
I personally don't have any global variables show up, have a friend who is able to test with Ghidra, they will post here shortly.

**Comment by arcturus-prime** [comment]
Searching globals variables by an address *in hexadecimal* does not work with this fix. With decimal, it does.

As a side note, I think a larger issue here is that global variables and types are in the same menu. That really doesn't make any sense. Types do not have an "address", and putting their name under that category instead of the actual "Name" category doesn't make any sense either. This leads to the code on lines 43-50, as well as the cause of the issue this pull request fixes.

**Comment by mahaloz** [comment]
Hmmmm @arcturus-prime, so in your mental model of reversing, (Enum, Structs) and (Global Vars) are in a completely different group? The real reason it was implemented like you see is because all of these Artifacts are not "tied" to a function. Anyone anywhere in the binary can use them. 

However, I am starting to come to your side. Perhaps we should have a panel just for `Types`, since Structs, Enums, and eventually Typedefs would just be types. They can't be used without a reference to a real object.

**Comment by ColdMeekly** [comment]
I will fix the incompatibility of this PR with variables and I agree that we should look into creating a separate `Types` panel, I would love to see that.

**Comment by ColdMeekly** [comment]
Tested working on IDA, waiting for the green signal from @arcturus-prime

**Comment by arcturus-prime** [comment]
@ColdMeekly Seems to work fine now. I can search by structure name for types and by address for global variables.

**Pull request merged**
